#ifndef ddbase_macro_ddeach_2__hpp_
#define ddbase_macro_ddeach_2__hpp_

#define ___DDEACH_CAT2(a, b) a ## b
#define __DDEACH_CAT2(a, b) a ## b
#define _DDEACH_CAT2(a, b) __DDEACH_CAT2(a, b)

#define _DDEACH_2_0(opt,   idx)
#define _DDEACH_2_1(opt,   idx, a, ...) opt(a, idx)
#define _DDEACH_2_2(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_1(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_3(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_2(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_4(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_3(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_5(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_4(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_6(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_5(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_7(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_6(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_8(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_7(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_9(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_8(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_10(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_9(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_11(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_10(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_12(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_11(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_13(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_12(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_14(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_13(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_15(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_14(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_16(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_15(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_17(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_16(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_18(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_17(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_19(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_18(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_20(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_19(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_21(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_20(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_22(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_21(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_23(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_22(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_24(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_23(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_25(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_24(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_26(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_25(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_27(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_26(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_28(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_27(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_29(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_28(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_30(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_29(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_31(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_30(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_32(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_31(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_33(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_32(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_34(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_33(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_35(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_34(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_36(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_35(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_37(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_36(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_38(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_37(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_39(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_38(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_40(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_39(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_41(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_40(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_42(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_41(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_43(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_42(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_44(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_43(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_45(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_44(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_46(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_45(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_47(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_46(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_48(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_47(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_49(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_48(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_50(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_49(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_51(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_50(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_52(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_51(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_53(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_52(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_54(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_53(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_55(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_54(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_56(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_55(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_57(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_56(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_58(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_57(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_59(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_58(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_60(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_59(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_61(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_60(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_62(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_61(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_63(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_62(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_64(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_63(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_65(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_64(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_66(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_65(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_67(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_66(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_68(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_67(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_69(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_68(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_70(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_69(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_71(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_70(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_72(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_71(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_73(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_72(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_74(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_73(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_75(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_74(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_76(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_75(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_77(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_76(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_78(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_77(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_79(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_78(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_80(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_79(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_81(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_80(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_82(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_81(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_83(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_82(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_84(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_83(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_85(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_84(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_86(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_85(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_87(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_86(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_88(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_87(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_89(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_88(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_90(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_89(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_91(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_90(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_92(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_91(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_93(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_92(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_94(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_93(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_95(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_94(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_96(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_95(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_97(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_96(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_98(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_97(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_99(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_98(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_2_100(opt, idx, a, ...) opt(a, idx) ___DDEACH_CAT2(_DDEACH_2_99(opt, DDINC(idx), __VA_ARGS__),)

#endif // ddbase_macro_ddeach_2__hpp_

