#ifndef ddbase_macro_ddeach_1__hpp_
#define ddbase_macro_ddeach_1__hpp_

#define ___DDEACH_CAT1(a, b) a ## b
#define __DDEACH_CAT1(a, b) a ## b
#define _DDEACH_CAT1(a, b) __DDEACH_CAT1(a, b)

// 为什么要加 ___DDEACH_CAT1: https://stackoverflow.com/questions/5134523/msvc-doesnt-expand-va-args-correctly

#define _DDEACH_1_0(opt,   idx)
#define _DDEACH_1_1(opt,   idx, a, ...) opt(a, idx)
#define _DDEACH_1_2(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_1(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_3(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_2(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_4(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_3(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_5(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_4(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_6(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_5(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_7(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_6(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_8(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_7(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_9(opt,   idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_8(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_10(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_9(opt,  DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_11(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_10(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_12(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_11(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_13(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_12(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_14(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_13(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_15(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_14(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_16(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_15(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_17(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_16(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_18(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_17(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_19(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_18(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_20(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_19(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_21(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_20(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_22(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_21(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_23(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_22(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_24(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_23(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_25(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_24(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_26(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_25(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_27(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_26(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_28(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_27(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_29(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_28(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_30(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_29(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_31(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_30(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_32(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_31(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_33(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_32(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_34(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_33(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_35(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_34(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_36(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_35(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_37(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_36(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_38(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_37(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_39(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_38(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_40(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_39(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_41(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_40(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_42(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_41(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_43(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_42(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_44(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_43(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_45(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_44(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_46(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_45(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_47(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_46(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_48(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_47(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_49(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_48(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_50(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_49(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_51(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_50(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_52(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_51(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_53(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_52(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_54(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_53(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_55(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_54(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_56(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_55(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_57(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_56(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_58(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_57(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_59(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_58(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_60(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_59(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_61(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_60(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_62(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_61(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_63(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_62(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_64(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_63(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_65(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_64(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_66(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_65(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_67(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_66(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_68(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_67(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_69(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_68(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_70(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_69(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_71(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_70(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_72(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_71(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_73(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_72(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_74(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_73(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_75(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_74(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_76(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_75(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_77(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_76(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_78(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_77(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_79(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_78(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_80(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_79(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_81(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_80(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_82(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_81(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_83(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_82(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_84(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_83(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_85(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_84(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_86(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_85(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_87(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_86(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_88(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_87(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_89(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_88(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_90(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_89(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_91(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_90(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_92(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_91(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_93(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_92(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_94(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_93(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_95(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_94(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_96(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_95(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_97(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_96(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_98(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_97(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_99(opt,  idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_98(opt, DDINC(idx), __VA_ARGS__),)
#define _DDEACH_1_100(opt, idx, a, ...) opt(a, idx) ___DDEACH_CAT1(_DDEACH_1_99(opt, DDINC(idx), __VA_ARGS__),)

#endif // ddbase_macro_ddeach_1__hpp_

